// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeybk9VbUNRVZsgONEVEpMcG8kJWS4C_A',
    appId: '1:693115835810:web:e8f8a871762e9722250efb',
    messagingSenderId: '693115835810',
    projectId: 'autisense-1aa08',
    authDomain: 'autisense-1aa08.firebaseapp.com',
    storageBucket: 'autisense-1aa08.firebasestorage.app',
    measurementId: 'G-KY65JZ5VNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-hXQgbkowtrCgLIbYghVQ54yTzjWkDA',
    appId: '1:693115835810:android:2c23047af7e74cf8250efb',
    messagingSenderId: '693115835810',
    projectId: 'autisense-1aa08',
    storageBucket: 'autisense-1aa08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASr5TOsFY4e8PLAH_hThlFzAyUzemaINU',
    appId: '1:693115835810:ios:07ac7f3c76ae0ef3250efb',
    messagingSenderId: '693115835810',
    projectId: 'autisense-1aa08',
    storageBucket: 'autisense-1aa08.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASr5TOsFY4e8PLAH_hThlFzAyUzemaINU',
    appId: '1:693115835810:ios:07ac7f3c76ae0ef3250efb',
    messagingSenderId: '693115835810',
    projectId: 'autisense-1aa08',
    storageBucket: 'autisense-1aa08.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeybk9VbUNRVZsgONEVEpMcG8kJWS4C_A',
    appId: '1:693115835810:web:31e13e782d27b855250efb',
    messagingSenderId: '693115835810',
    projectId: 'autisense-1aa08',
    authDomain: 'autisense-1aa08.firebaseapp.com',
    storageBucket: 'autisense-1aa08.firebasestorage.app',
    measurementId: 'G-R5DK6571TK',
  );
}
